### PR TITLE
Aquarium state

### PR DESCRIPTION
**Pull request by Jossl123**
add some aquarium data so that we can store some information about some clicks events made by the user, like clicked bot, ...

(I just added the data, there's no testable stuff to do in this PR)

### CODE REVIEW

**Comment by dalestee** [comment]
maybe implement the feature that uses the data, so that after merging we dont have just useless data with no feature using it

**Comment by Jossl123** [comment]
I implemented a feature that uses the data, now you can click one of our bot and it will be put into the aquarium variables

**Comment by dalestee** [comment]
nice well DONE! :smile:

**Review by dalestee — APPROVED** [review]
:+1:

**Pull request merged**
